disable_response_storage = true
model = "doubao-seed-2.1-turbo"
model_provider = "arkcli-agent-plan"
model_reasoning_effort = "high"
model_catalog_json = "~/.codex/models.json"

[marketplaces]
  [marketplaces.claude-code-workflows]
    last_revision = "d6837ae274c2cd817acad3fb98f193a4390a4c3e"
    last_updated = "2026-08-18T01:09:44Z"
    source = "https://github.com/wshobson/agents.git"
    source_type = "git"

[model_providers]
  [model_providers.arkcli-agent-plan]
    base_url = "https://ark.cn-beijing.volces.com/api/plan/v3"
    env_key = "ARK_BEARER_TOKEN"
    name = "Volcano Engine (Agent Plan)"
    wire_api = "responses"

[plugins]
  [plugins."python-development@claude-code-workflows"]
    enabled = true

[tui]
  [tui.model_availability_nux]
    "gpt-5.6-sol" = 4
